export interface SeedProperty {
  id: number;
  title: string;
  slug: string;
  price: number;
  type: string;
  status: string;
  label: string;
  beds: number;
  baths: number;
  sqft: number;
  image: string;
  description: string;
  location: string;
  state: string;
  featured: boolean;
  createdAt: string;
}

export interface SeedAgent {
  id: number;
  name: string;
  slug: string;
  phone: string;
  phone2: string;
  whatsapp: string;
  email: string;
  image: string;
  title: string;
  bio: string;
  verified: boolean;
  listings: number[];
}

export interface SeedPost {
  id: number;
  title: string;
  slug: string;
  category: string;
  date: string;
  image: string;
  excerpt: string;
  content: string;
}

export const propertiesSeed: SeedProperty[] = [
  {
    id: 1,
    title: 'Comfortable Family Home',
    slug: 'comfortable-family-home',
    price: 550000,
    type: 'Apartments',
    status: 'For Sale',
    label: 'Hot Offer',
    beds: 2,
    baths: 2,
    sqft: 2760,
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80',
    description: 'A beautiful comfortable family home located in a quiet neighborhood with excellent schools and amenities nearby. Recently renovated kitchen and bathrooms, hardwood floors throughout, and a spacious backyard perfect for entertaining.',
    location: 'New York',
    state: 'New York',
    featured: true,
    createdAt: '2026-01-12T10:00:00.000Z',
  },
  {
    id: 2,
    title: 'Historic Villa',
    slug: 'historic-villa',
    price: 3700000,
    type: 'Villa',
    status: 'For Sale',
    label: '',
    beds: 2,
    baths: 2,
    sqft: 2170,
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80',
    description: 'A stunning historic villa with classic architecture and modern amenities. Perfect for luxury living, featuring ornate ceilings, a private garden, and breathtaking views of the surrounding hills.',
    location: 'Los Angeles',
    state: 'California',
    featured: true,
    createdAt: '2026-01-15T10:00:00.000Z',
  },
  {
    id: 3,
    title: 'Villa for Sale',
    slug: 'villa-for-sale',
    price: 1750000,
    type: 'Villa',
    status: 'For Sale',
    label: '',
    beds: 4,
    baths: 2,
    sqft: 4100,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    description: "Spacious villa with modern design, large backyard, and premium finishes throughout. Open-concept living, chef's kitchen, and a resort-style pool make this a true entertainer's dream.",
    location: 'Miami',
    state: 'Florida',
    featured: true,
    createdAt: '2026-01-18T10:00:00.000Z',
  },
  {
    id: 4,
    title: 'Villa with Pool',
    slug: 'villa-with-pool',
    price: 3900000,
    type: 'Villa',
    status: 'For Sale',
    label: '',
    beds: 5,
    baths: 2,
    sqft: 3450,
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80',
    description: 'Luxurious villa with a stunning pool, landscaped garden, and breathtaking views. Floor-to-ceiling windows flood the home with natural light and frame the ocean horizon.',
    location: 'Miami',
    state: 'Florida',
    featured: true,
    createdAt: '2026-01-20T10:00:00.000Z',
  },
  {
    id: 5,
    title: 'Villa Relaxing Green View',
    slug: 'villa-relaxing-green-view',
    price: 7599000,
    type: 'Villa',
    status: 'For Sale',
    label: '',
    beds: 3,
    baths: 2,
    sqft: 2540,
    image: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=800&q=80',
    description: 'Elegant villa surrounded by lush greenery offering peace and tranquility. A sanctuary for those who value privacy, nature, and refined architecture in equal measure.',
    location: 'Los Angeles',
    state: 'California',
    featured: true,
    createdAt: '2026-01-22T10:00:00.000Z',
  },
  {
    id: 6,
    title: 'Modern Apartment',
    slug: 'modern-apartment',
    price: 97000,
    type: 'Apartment',
    status: 'For Sale',
    label: '',
    beds: 1,
    baths: 2,
    sqft: 1560,
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
    description: 'Sleek modern apartment with bay views, open floor plan, and top-of-the-line finishes. building amenities include a gym, rooftop lounge, and 24/7 concierge.',
    location: 'New York',
    state: 'New York',
    featured: true,
    createdAt: '2026-01-25T10:00:00.000Z',
  },
  {
    id: 7,
    title: 'Comfortable Family Home Test',
    slug: 'comfortable-family-home-test',
    price: 550000,
    type: 'Single Family Home',
    status: 'For Sale',
    label: '',
    beds: 2,
    baths: 2,
    sqft: 2760,
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=80',
    description: 'Charming family home with modern amenities and a spacious backyard. Move-in ready with a freshly painted interior and a new roof installed in 2025.',
    location: 'Chicago',
    state: 'Illinois',
    featured: false,
    createdAt: '2026-01-28T10:00:00.000Z',
  },
  {
    id: 8,
    title: 'Luxury Apartment Bay View',
    slug: 'luxury-apartment-bay-view',
    price: 450000,
    type: 'Apartment',
    status: 'For Sale',
    label: 'Hot Offer',
    beds: 1,
    baths: 2,
    sqft: 2149,
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
    description: 'Luxury apartment with panoramic bay views, modern kitchen, and premium amenities. Wake up to the water every morning from your wraparound balcony.',
    location: 'San Francisco',
    state: 'California',
    featured: false,
    createdAt: '2026-02-01T10:00:00.000Z',
  },
  {
    id: 9,
    title: 'Modern Studio Apartment',
    slug: 'modern-studio-apartment',
    price: 1200,
    type: 'Studio',
    status: 'For Rent',
    label: '',
    beds: 1,
    baths: 1,
    sqft: 650,
    image: 'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&w=800&q=80',
    description: 'Cozy studio apartment in the heart of the city, perfect for young professionals. Steps from transit, cafes, and nightlife with all utilities included.',
    location: 'New York',
    state: 'New York',
    featured: false,
    createdAt: '2026-02-03T10:00:00.000Z',
  },
  {
    id: 10,
    title: 'Commercial Office Space',
    slug: 'commercial-office-space',
    price: 5000,
    type: 'Office',
    status: 'For Rent',
    label: '',
    beds: 0,
    baths: 2,
    sqft: 2000,
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    description: 'Prime office space in downtown business district with modern facilities. Open floor plan, meeting rooms, and high-speed fiber internet ready to go.',
    location: 'Manhattan',
    state: 'New York',
    featured: false,
    createdAt: '2026-02-05T10:00:00.000Z',
  },
  {
    id: 11,
    title: 'Skyline Penthouse',
    slug: 'skyline-penthouse',
    price: 4200000,
    type: 'Penthouse',
    status: 'For Sale',
    label: 'Hot Offer',
    beds: 3,
    baths: 3,
    sqft: 3800,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    description: 'Breathtaking penthouse crowning a landmark tower with 360-degree city views, private elevator access, and a wraparound terrace built for entertaining.',
    location: 'New York',
    state: 'New York',
    featured: true,
    createdAt: '2026-02-08T10:00:00.000Z',
  },
  {
    id: 12,
    title: 'Cozy Suburban Townhouse',
    slug: 'cozy-suburban-townhouse',
    price: 680000,
    type: 'Townhouse',
    status: 'For Sale',
    label: '',
    beds: 3,
    baths: 2,
    sqft: 2200,
    image: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80',
    description: 'Charming townhouse in a friendly community with a private garage, rooftop deck, and shared green space. Ideal for growing families seeking comfort and convenience.',
    location: 'Oak Park',
    state: 'Illinois',
    featured: false,
    createdAt: '2026-02-10T10:00:00.000Z',
  },
  {
    id: 13,
    title: 'Beachfront Condo',
    slug: 'beachfront-condo',
    price: 2150000,
    type: 'Condo',
    status: 'For Sale',
    label: '',
    beds: 2,
    baths: 2,
    sqft: 1680,
    image: 'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&w=800&q=80',
    description: 'Wake up to the sound of waves in this beachfront condo with direct sand access, floor-to-ceiling glass, and a building rooftop infinity pool.',
    location: 'Miami',
    state: 'Florida',
    featured: true,
    createdAt: '2026-02-12T10:00:00.000Z',
  },
  {
    id: 14,
    title: 'Modern Loft Downtown',
    slug: 'modern-loft-downtown',
    price: 3200,
    type: 'Loft',
    status: 'For Rent',
    label: '',
    beds: 1,
    baths: 1,
    sqft: 1100,
    image: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80',
    description: 'Industrial-chic loft with exposed brick, 14-foot ceilings, and skyline views. A rare rental in the arts district with in-unit laundry and parking.',
    location: 'Chicago',
    state: 'Illinois',
    featured: false,
    createdAt: '2026-02-14T10:00:00.000Z',
  },
  {
    id: 15,
    title: 'Prime Retail Space',
    slug: 'prime-retail-space',
    price: 8500,
    type: 'Shop',
    status: 'For Rent',
    label: '',
    beds: 0,
    baths: 1,
    sqft: 2600,
    image: 'https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?auto=format&fit=crop&w=800&q=80',
    description: 'High-visibility retail space on a busy boulevard with massive storefront windows, built-out fitting rooms, and heavy foot traffic daily.',
    location: 'Los Angeles',
    state: 'California',
    featured: false,
    createdAt: '2026-02-16T10:00:00.000Z',
  },
  {
    id: 16,
    title: 'Lakeside Land Plot',
    slug: 'lakeside-land-plot',
    price: 340000,
    type: 'Land',
    status: 'For Sale',
    label: '',
    beds: 0,
    baths: 0,
    sqft: 43560,
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
    description: 'Build your dream home on this level lakeside parcel with approved permits, utilities at the street, and unobstructed water views from every angle.',
    location: 'SHAHJADPUR',
    state: 'Illinois',
    featured: false,
    createdAt: '2026-02-18T10:00:00.000Z',
  },
];

export const agentsSeed: SeedAgent[] = [
  {
    id: 1,
    name: 'Brittany Watkins',
    slug: 'brittany-watkins',
    phone: '789 456 3210',
    phone2: '321 456 9874',
    whatsapp: '3214569874',
    email: 'brittany@expressrealtyprime.com',
    image: 'https://randomuser.me/api/portraits/women/44.jpg',
    title: 'Real Estate Agent',
    bio: 'Brittany has over 10 years of experience in luxury residential real estate. She specializes in helping families find their dream homes and has closed more than 300 transactions across the tri-state area.',
    verified: false,
    listings: [1, 6, 11],
  },
  {
    id: 2,
    name: 'Michelle Ramirez',
    slug: 'michelle-ramirez',
    phone: '789 456 3210',
    phone2: '321 456 9874',
    whatsapp: '3214569874',
    email: 'michelle@expressrealtyprime.com',
    image: 'https://randomuser.me/api/portraits/women/68.jpg',
    title: 'Senior Real Estate Agent',
    bio: 'Michelle is a top-performing agent with expertise in commercial and residential properties across New York. She is known for sharp negotiation and white-glove client service.',
    verified: false,
    listings: [3, 4, 13],
  },
  {
    id: 3,
    name: 'Mike Moore',
    slug: 'mike-moore',
    phone: '789 456 3210',
    phone2: '897 654 1258',
    whatsapp: '3214569874',
    email: 'mike@expressrealtyprime.com',
    image: 'https://randomuser.me/api/portraits/men/32.jpg',
    title: 'Real Estate Agent',
    bio: 'Mike brings years of market analysis and negotiation experience to help clients get the best deals. He treats every transaction as if it were his own investment.',
    verified: false,
    listings: [2, 5],
  },
  {
    id: 4,
    name: 'Patricia Fuller',
    slug: 'patricia-fuller',
    phone: '789 456 3210',
    phone2: '321 456 9874',
    whatsapp: '3214569874',
    email: 'patricia@expressrealtyprime.com',
    image: 'https://randomuser.me/api/portraits/women/26.jpg',
    title: 'Luxury Property Specialist',
    bio: 'Patricia specializes in high-end luxury properties and has closed over $100M in transactions. Her discretion and attention to detail are unmatched.',
    verified: true,
    listings: [7, 8],
  },
  {
    id: 5,
    name: 'David Chen',
    slug: 'david-chen',
    phone: '789 456 3390',
    phone2: '321 456 1122',
    whatsapp: '3214561122',
    email: 'david@expressrealtyprime.com',
    image: 'https://randomuser.me/api/portraits/men/45.jpg',
    title: 'Senior Investment Advisor',
    bio: 'David helps investors build diversified real estate portfolios. With a background in finance, he pairs market data with on-the-ground insight to maximize returns.',
    verified: true,
    listings: [10, 14, 15],
  },
  {
    id: 6,
    name: 'Sarah Johnson',
    slug: 'sarah-johnson',
    phone: '789 456 7788',
    phone2: '321 456 3344',
    whatsapp: '3214563344',
    email: 'sarah@expressrealtyprime.com',
    image: 'https://randomuser.me/api/portraits/women/65.jpg',
    title: 'First-Time Buyer Specialist',
    bio: 'Sarah guides first-time buyers through every step with patience and clarity. She loves turning renters into proud homeowners and demystifying the mortgage process.',
    verified: false,
    listings: [9, 12, 16],
  },
];

export const postsSeed: SeedPost[] = [
  {
    id: 1,
    title: 'Skills That You Can Learn In The Real Estate Market',
    slug: 'skills-that-you-can-learn-in-the-real-estate-market',
    category: 'Business',
    date: 'March 9, 2016',
    image: 'https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?auto=format&fit=crop&w=800&q=80',
    excerpt: 'From negotiation to market analysis, the real estate industry teaches transferable skills that benefit every professional.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis et sem sed sollicitudin. Donec auctor, felis nec volutpat fermentum, nunc nunc tincidunt nunc, vitae aliquam nisl nunc vitae nunc. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Real estate rewards those who master communication, perseverance, and financial literacy.',
  },
  {
    id: 2,
    title: 'Learn The Truth About Real Estate Industry',
    slug: 'learn-the-truth-about-real-estate-industry',
    category: 'Construction',
    date: 'March 9, 2016',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Separating myths from facts so you can make confident, informed property decisions.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis et sem sed sollicitudin. Donec auctor, felis nec volutpat fermentum, nunc nunc tincidunt nunc, vitae aliquam nisl nunc vitae nunc. The truth is that real estate is a long-term game built on relationships, not transactions. Understanding the fundamentals protects you from hype.',
  },
  {
    id: 3,
    title: '10 Quick Tips About Business Development',
    slug: '10-quick-tips-about-business-development',
    category: 'Real Estate',
    date: 'March 9, 2016',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Practical strategies to grow your real estate business without burning out.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis et sem sed sollicitudin. Donec auctor, felis nec volutpat fermentum, nunc nunc tincidunt nunc, vitae aliquam nisl nunc vitae nunc. Focus on consistency, nurture your database, and let referrals become your engine for growth.',
  },
  {
    id: 4,
    title: '14 Common Misconceptions About Business Development',
    slug: '14-common-misconceptions-about-business-development',
    category: 'Real Estate',
    date: 'March 9, 2016',
    image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Why the usual advice about growing a business often misses the mark.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mollis et sem sed sollicitudin. Donec auctor, felis nec volutpat fermentum, nunc nunc tincidunt nunc, vitae aliquam nisl nunc vitae nunc. Growth is rarely linear, and the best developers embrace experimentation over perfection.',
  },
  {
    id: 5,
    title: "How to Stage Your Home for a Faster Sale",
    slug: 'how-to-stage-your-home-for-a-faster-sale',
    category: 'Home & Living',
    date: 'January 20, 2026',
    image: 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Small staging changes can add thousands to your final sale price and shrink your time on market.',
    content: 'Staging is about helping buyers picture themselves in the home. Declutter first, then add warm lighting, neutral textiles, and a few statement pieces. Curb appeal matters just as much as the interior, so refresh landscaping and the front door before showings.',
  },
  {
    id: 6,
    title: "First-Time Buyer's Guide to Mortgages",
    slug: 'first-time-buyers-guide-to-mortgages',
    category: 'Finance',
    date: 'January 28, 2026',
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Everything you need to know about rates, down payments, and getting pre-approved.',
    content: "Getting pre-approved is the first real step toward homeownership. Compare fixed and adjustable rates, understand your debt-to-income ratio, and remember that the lowest rate is not always the lowest total cost. A trusted lender will walk you through the fine print.",
  },
  {
    id: 7,
    title: 'Top Neighborhoods to Watch in 2026',
    slug: 'top-neighborhoods-to-watch-in-2026',
    category: 'Market Trends',
    date: 'February 4, 2026',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Where smart buyers are planting roots this year and why prices are moving.',
    content: "Transit-adjacent districts and walkable suburbs are leading 2026's growth. Look for areas with new infrastructure, strong schools, and a budding restaurant scene. The best time to buy is often before the crowd notices.",
  },
  {
    id: 8,
    title: 'Understanding Property Taxes Like a Pro',
    slug: 'understanding-property-taxes-like-a-pro',
    category: 'Finance',
    date: 'February 11, 2026',
    image: 'https://images.unsplash.com/photo-1543286386-713bdd548da4?auto=format&fit=crop&w=800&q=80',
    excerpt: 'Demystifying assessments, exemptions, and how taxes affect your monthly payment.',
    content: 'Property taxes fund local services and vary widely by location. Review your assessment annually, claim any available homestead exemptions, and factor taxes into your true monthly cost of ownership before making an offer.',
  },
];
